# VanCode - A fast, extensible bytecode generator and VM for building
# Domain-Specific Languages (DSLs), or general-purpose programming language
#
# Powered by Nim.
#
# (c) iLiquid, 2019-2020
#     https://github.com/liquidev/
#
# (c) 2025 George Lemon | MIT License
#          Made by Humans from OpenPeeps
#          https://github.com/openpeeps/vancode

## We are implementing a stack-based Virtual Machine to execute bytecode
## generated by the VanCode compiler. The VM is designed to be simple
## and portable, easily embeddable in other Nim applications or projects
## that want to build DSL (domain-specific language) features on top
## of the VanCode framework.

import std/[strutils, tables, critbits, algorithm,
          json, options, hashes, dynlib, sysatomics]

import pkg/voodoo/extensibles
import ./chunk, ./value

when defined(hayaVmWriteStackOps):
  import pkg/kapsis/interactive/prompts

macro conditionalPlaceholder(id: static string) =
  if ExtendableProcBodies.contains(id):
    result = nnkBlockStmt.newTree(
      ident("VoodooInjectedSnippet_" & id),
      ExtendableProcBodies[id]
    )
  else:
    result = newStmtList()

type
  VMPreferences* = object
    ## Preferences for configuring the VM's behavior. These can be set when creating a new VM instance
    enableHotCodeDetection*: bool
    hotProcThreshold*: int = 10
    hotChunkThreshold*: int = 100
    hotLoopThreshold*: int = 500

  CallFrame* = tuple
    ## Represents a call frame for function/procedure calls.
    currentChunk: Chunk
    cachedOps: CachedOps
    pcIdx: int
    stackBottom: int
    script: Script

  CoroutineState* = enum
    csCreated
    csSuspended
    csRunning
    csCompleted
    csErrored

  Coroutine* {.acyclic.} = ref object
    state*: CoroutineState
    callee*: Proc
    script*: Script
    savedStack*: seq[Value]
    savedCallStack*: seq[CallFrame]
    savedPcIdx*: int
    savedChunk*: Chunk
    savedCachedOps*: CachedOps
    savedStackBottom*: int
    result*: Value

  CoroutineResultKind* = enum
    crYielded
    crCompleted
    crErrored

  CoroutineResult* = object
    case kind*: CoroutineResultKind
    of crYielded: yieldedValue*: Value
    of crCompleted: resultValue*: Value
    of crErrored: errorMsg*: string

  ArgKind = enum
    akNone, akInt, akFloat, akString

  CachedOps* = ref object
    opcodes*: seq[Opcode]
    arg1*: seq[int64]
    arg2*: seq[int64]
    flags*: seq[int16]
    byteOffsets*: seq[int]
    jumpTargets*: seq[int]

  Vm* {.acyclic.} = ref object
    ## The main VM object that holds the execution state and caches
    lvl: int
    opCache: Table[Hash, CachedOps]
    hotCounts*: Table[string, int]
    hotProcCounts*: Table[string, int]

    preferences: VMPreferences
    importedModules*: Table[string, Script]
    activeCoroutine*: Coroutine
    savedStack: seq[Value]
    savedCallStack: seq[CallFrame]
    savedPcIdx: int
    savedChunk: Chunk
    savedCo: CachedOps
    savedStackBottom: int
    savedScript: Script
    jit*: JitHooks
    pendingCallback*: Value

const
  VMInitialPreallocatedStackSize* {.intdefine.} = 64
    ## initial size of the VM's evaluation stack. this is just an optimization to avoid
    ## frequent resizing during execution of small chunks. it can grow dynamically if needed.
  VMPreallocatedStackSize* {.intdefine.} = 16
    ## number of stack slots to preallocate when growing the stack. this is just an optimization to avoid
    ## frequent resizing during execution of small chunks. it can grow dynamically if needed.

proc newVm*(): Vm =
  Vm()

proc getHotProcCount*(vm: Vm, procName: string): int =
  vm.hotProcCounts.getOrDefault(procName)

proc getHotChunkCount*(vm: Vm, chunk: Chunk): int =
  vm.hotCounts.getOrDefault($chunk)

proc newVirtualMachine*(prefs: VMPreferences): Vm =
  ## Create a new VM instance with optional preferences. If preferences are not
  ## provided, defaults will be used.
  result = VM(preferences: prefs)

proc `{}`[T](x: seq[T], i: int): ptr UncheckedArray[T] =
  result = cast[ptr UncheckedArray[T]](x[i].unsafeAddr)

proc `{}`[T](x: seq[T], i: BackwardsIndex): ptr UncheckedArray[T] =
  result = x{x.len - i.int}

proc read[T](code: ptr UncheckedArray[uint8], offset: int): T =
  result = cast[ptr T](code[offset].unsafeAddr)[]

proc push(stack: var Stack, val: Value) =
  let i = stack.len
  stack.setLen(i + 1)
  stack[i] = val
  
  # additional debug output for stack operations
  when defined(hayaVmWriteStackOps):
    display(span("push", fgCyan), span($stack))

proc pop(stack: var Stack): Value =
  # additional debug output for stack operations
  when defined(hayaVmWriteStackOps):
    display(span("pop", fgCyan), span($stack[^1]))

  result = stack[^1]
  stack.setLen(stack.len - 1)

proc peek(stack: Stack): Value =
  result = stack[^1]

template inc[T](p: ptr UncheckedArray[T], offset = 1) =
  p = cast[ptr UncheckedArray[T]](cast[int](p) + offset)

template dec[T](p: ptr UncheckedArray[T], offset = 1) =
  p = cast[ptr UncheckedArray[T]](cast[int](p) - offset)

# Bit helpers
template packFlags(a1, a2: ArgKind): int16 =
  (ord(a1) or (ord(a2) shl 2)).int16

template arg1Kind(f: int16): ArgKind = ArgKind((f and 0b11).int)
template arg2Kind(f: int16): ArgKind = ArgKind(((f shr 2) and 0b11).int)

#
# Forward declarations
#
proc parseChunk(currentChunk: Chunk): CachedOps

# proc ffiTypeFor(typeId: TypeId): ptr Type =
#   # FFI helpers
#   case typeId
#   of tyBool, tyInt: addr type_sint64
#   of tyFloat: addr type_double
#   of tyString: addr type_pointer
#   of tyPointer: addr type_pointer
#   else: addr type_void

# Hot code detection
proc markHot(vm: Vm, currentChunk: Chunk) =
  if vm.preferences.enableHotCodeDetection and currentChunk != nil:
    vm.hotCounts.mgetOrPut($currentChunk, 0).inc

proc markHotProc(vm: Vm, theProc: Proc) =
  if vm.preferences.enableHotCodeDetection and theProc != nil:
    theProc.jitCallCount.inc
    if theProc.jitCallCount == vm.preferences.hotProcThreshold:
      if vm.jit.queueCompile != nil:
        vm.jit.queueCompile(cast[pointer](theProc))
      elif vm.jit.getForeign != nil:
        let jitFn = vm.jit.getForeign(cast[pointer](theProc))
        if jitFn != nil:
          theProc.jitForeign = jitFn

proc parseChunk(currentChunk: Chunk): CachedOps =
  # Parsing raw bytecode into operations
  var pc = currentChunk.code{0}
  let base = cast[int](pc)
  let codeLen = currentChunk.code.len

  proc readArg[T](pc: var ptr UncheckedArray[uint8]): T =
    # reads an argument of type T and advances the pointer
    result = pc.read[:T](0); inc(pc, sizeof(T))

  proc seekArg[T](pc: var ptr UncheckedArray[uint8]): T =
    # reads an argument of type T without advancing the pointer
    result = pc.read[:T](0)

  var
    opcodes: seq[Opcode]
    arg1: seq[int64]
    arg2: seq[int64]
    flags: seq[int16]
    byteOffsets: seq[int]
    jumpTargets: seq[int]

  template addOp(oc: Opcode, a1: int64 = 0'i64, a2: int64 = 0'i64,
              k1: ArgKind = akNone, k2: ArgKind = akNone) =
    opcodes.add(oc)
    arg1.add(a1)
    arg2.add(a2)
    flags.add(packFlags(k1, k2))
    byteOffsets.add(opByteOffset)
    jumpTargets.add(-1)

  while cast[int](pc) - base < codeLen:
    let opByteOffset = cast[int](pc) - base
    let oc = Opcode(pc[0])
    inc(pc)
    extendableCase "vmParseChunkCase":
      case oc
      of opcPushNil:
        let id = readArg[uint16](pc) # object id
        addOp(oc, id.int64, 0, akInt)
      of opcPushI:
        let v = readArg[int](pc)
        addOp(oc, v.int64, 0, akInt)
      of opcPushF:
        let v = readArg[float64](pc)
        addOp(oc, cast[int64](v), 0, akFloat)
      of opcPushS:
        let sid = readArg[uint16](pc)
        addOp(oc, sid.int64, 0, akString)
      of opcPushPointer:
        discard readArg[pointer](pc)
        addOp(oc)
      of opcPushTrue, opcPushFalse, opcConcatStr:
        addOp(oc)
      of opcPushG, opcPopG:
        let sid = readArg[uint16](pc)
        addOp(oc, sid.int64, 0, akString)
      of opcPushL, opcPopL, opcIncL, opcDecL:
        let idx = readArg[uint8](pc).int
        addOp(oc, idx.int64, 0, akInt)
      of opcJumpFwd, opcJumpFwdT, opcJumpFwdF, opcJumpBack:
        let dist = readArg[uint16](pc).int
        addOp(oc, dist.int64, 0, akInt)
      of opcCallD:
        let filePathIdx = readArg[uint16](pc)
        let pid = readArg[uint16](pc).int
        addOp(oc, filePathIdx.int64, pid.int64, akString, akInt)
      of opcPushProc:
        let filePathIdx = readArg[uint16](pc)
        let pid = readArg[uint16](pc).int
        addOp(oc, filePathIdx.int64, pid.int64, akString, akInt)
      of opcCallI:
        let argc = readArg[uint8](pc).int
        addOp(oc, argc.int64, 0, akInt)
      of opcConstrArray, opcConstrObj:
        let cnt = readArg[uint16](pc).int
        addOp(oc, cnt.int64, 0, akInt)
      of opcDiscard:
        let n = readArg[uint8](pc).int
        addOp(oc, n.int64, 0, akInt)
      of opcGetF, opcSetF:
        let f = readArg[uint8](pc).int
        addOp(oc, f.int64, 0, akInt)
      # of opcFFIGetProc:
      #   let sid = readArg[uint16](pc)
      #   let argc = readArg[uint8](pc).int
      #   addOp(oc, sid.int64, argc.int64, akString, akInt)
      of opcImportModule:
        let sid = readArg[uint16](pc)
        addOp(oc, sid.int64, 0, akString)
      of opcCreateCoro:
        let pid = readArg[uint16](pc)
        addOp(oc, pid.int64, 0, akInt)
      else:
        addOp(oc)

  # Precompute jump targets
  var byteToOp = newSeq[int](codeLen)
  for i in 0..<codeLen:
    byteToOp[i] = -1
  
  for i, b in byteOffsets:
    if b >= 0 and b < codeLen:
      byteToOp[b] = i

  for i, oc in opcodes:
    case oc
    of opcJumpFwd, opcJumpFwdT, opcJumpFwdF:
      let dist = arg1[i].int
      let operandStart = byteOffsets[i] + 1
      let targetByte = operandStart + (dist - 1)
      if targetByte >= 0 and targetByte < codeLen:
        let j = byteToOp[targetByte]
        if j != -1: jumpTargets[i] = j
    of opcJumpBack:
      let dist = arg1[i].int
      let targetByte = byteOffsets[i] - dist
      if targetByte >= 0 and targetByte < codeLen:
        let j = byteToOp[targetByte]
        if j != -1: jumpTargets[i] = j
    else: discard # no jump target

  # sanity check — ensure all arrays are same length
  if opcodes.len != arg1.len or opcodes.len != arg2.len or opcodes.len != flags.len or opcodes.len != byteOffsets.len or opcodes.len != jumpTargets.len:
    raise newException(IndexDefect, "parseChunk: cached ops arrays out-of-sync: opcodes=" & $opcodes.len &
            " arg1=" & $arg1.len & " arg2=" & $arg2.len & " flags=" & $flags.len & " off=" & $byteOffsets.len & " jmp=" & $jumpTargets.len)

  result = CachedOps(
    opcodes: opcodes,
    arg1: arg1,
    arg2: arg2,
    flags: flags,
    byteOffsets: byteOffsets,
    jumpTargets: jumpTargets
  )

#
# Cache layer uses new parse
#
proc getCachedOps*(vm: Vm, currentChunk: Chunk): CachedOps =
  # let key = cast[pointer](currentChunk)
  let hashed = hash(currentChunk)
  if vm.opCache.contains(hashed):
    when defined(hayaVmWriteStackOps):
      display(span("cached_ops:", fgGreen), span("chunk=" & $currentChunk))
    return vm.opCache[hashed] # already cached
  result = parseChunk(currentChunk)
  vm.opCache[hashed] = result

#
# Decoders
#
template getArg1Int*(co: CachedOps, i: int): int =
  co.arg1[i].int

template getArg1Float*(co: CachedOps, i: int): float64 =
  cast[float64](co.arg1[i])

template getArg1Str(co: CachedOps, i: int, currentChunk: Chunk): string =
  let id = co.arg1[i].uint16
  if id < uint16(currentChunk.strings.len):
    currentChunk.strings[id]
  else:
    raise newException(IndexDefect, "String index " & $id & " out of bounds for chunk " & $currentChunk)

template pushConst(co: CachedOps, i: int, currentChunk: Chunk, stack: var Stack) =
  let k = co.flags[i].arg1Kind
  case k
  of akInt:
    stack.push(initValue(co.getArg1Int(i)))
  of akFloat:
    stack.push(initValue(co.getArg1Float(i)))
  of akString:
    stack.push(initValue(co.getArg1Str(i, currentChunk)))
  else: discard
  
  # additional debug output for stack operations
  when defined(hayaVmWriteStackOps):
    echo "PushConst: opcode=", oc, " value=", stack[^1]

proc prewarmScriptOpsRec(vm: Vm, s: Script, seen: var Table[Hash, bool]) =
  # Recursively prewarm cached ops for all chunks
  # in the script and its imports.
  if s.isNil: return
  let h = hash(s)
  if seen.hasKey(h): return # already prewarmed this script (handles cycles in imports)
  seen[h] = true

  if not s.mainChunk.isNil:
    vm.importedModules[s.mainChunk.file] = s
    discard vm.getCachedOps(s.mainChunk)

  for p in s.procs:
    if p.kind == pkNative and not p.chunk.isNil:
      discard vm.getCachedOps(p.chunk)

  for modPath, modScript in s.scripts:
    vm.importedModules[modPath] = modScript
    vm.prewarmScriptOpsRec(modScript, seen)

proc prewarmScriptOps*(vm: Vm, s: Script) =
  ## Call this once after loading from persistent cache
  ## (or after compile) to prewarm the VM's opcode cache
  ## with all chunks in the script and its imports
  var seen = initTable[Hash, bool]()
  vm.prewarmScriptOpsRec(s, seen)

proc interpret*(vm: Vm, script: Script, startChunk: Chunk,
        args: openArray[Value] = [],
        staticString: Option[string] = none(string),
        globaldata = newJObject(),
        localData = newJObject(),
        stepping: Coroutine = nil): Value {.discardable.} =
  ## Interpret the given chunk in the context of the provided script.
  ## If `stepping` is provided, the VM runs the coroutine from its saved state
  ## until it yields or completes, then returns the yielded/completed value.
  var
    stack: Stack = newSeqOfCap[Value](VMInitialPreallocatedStackSize)
    callStack: seq[CallFrame] = newSeqOfCap[CallFrame](256)
    script = script
    currentChunk  = startChunk
    cached = vm.getCachedOps(currentChunk)
    co = cached
    opcodes = co.opcodes
    pcIdx  = 0
    stackBottom = 0
    frameChanged = false
  for a in args:
    stack.add(a)

  # If stepping a coroutine, override state from the coroutine
  if stepping != nil:
    case stepping.state
    of csSuspended:
      stack = stepping.savedStack
      callStack = stepping.savedCallStack
      pcIdx = stepping.savedPcIdx
      currentChunk = stepping.savedChunk
      co = stepping.savedCachedOps
      cached = co
      opcodes = co.opcodes
      stackBottom = stepping.savedStackBottom
      script = stepping.script
    of csCreated:
      let p = stepping.callee
      if stepping.savedStack.len > 0:
        stack = stepping.savedStack
        callStack = stepping.savedCallStack
        stackBottom = stepping.savedStackBottom
      else:
        stack = newSeqOfCap[Value](VMInitialPreallocatedStackSize)
        callStack = newSeqOfCap[CallFrame](256)
        stackBottom = 0
      currentChunk = p.chunk
      co = vm.getCachedOps(currentChunk)
      cached = co
      opcodes = co.opcodes
      pcIdx = 0
      script = stepping.script
    else:
      raise newException(ValueError,
        "interpret: cannot step a coroutine in state " & $stepping.state)
    stepping.state = csRunning

  # initialize globals with provided data
  # this is a Tim-specific hack and must be rethought for a more
  # general VM design. for now we just want to get Tim's rendering working with
  var globals = Table[string, Value]()
  globals["app"] = initValue(globalData)
  globals["this"] = initValue(localData)

  when defined(vancodeJit) or defined(vancodeJitLlvm):
    if vm.jit.setGlobalsPtr != nil:
      vm.jit.setGlobalsPtr(addr globals)

  template unary(expr) =
    let a {.inject.} = stack.pop()
    stack.push(initValue(expr))
    
    # additional debug output for stack operations
    when defined(hayaVmWriteStackOps):
      echo "unary op: ", expr, " a=", a

  template binary(someVal, op) =
    let b {.inject.} = stack.pop()
    let a {.inject.} = stack.pop()
    if a.typeId == tyInt and b.typeId == tyInt:
      stack.push(initValue(op(a.someVal, b.someVal)))
    elif a.typeId == tyFloat and b.typeId == tyFloat:
      stack.push(initValue(op(a.someVal, b.someVal)))
    elif a.typeId == tyInt and b.typeId == tyFloat:
      stack.push(initValue(op(toFloat(a.intVal), b.floatVal)))
    elif a.typeId == tyFloat and b.typeId == tyInt:
      stack.push(initValue(op(a.floatVal, toFloat(b.intVal))))
    else:
      stack.push(initValue(op(a.someVal, b.someVal)))
    
    # additional debug output for stack operations
    when defined(hayaVmWriteStackOps):
      echo "binary op: ", op, " a=", a, " b=", b

  template binaryInplNumber(someVal, op) =
    let b {.inject.} = stack.pop()
    let a {.inject.} = stack.pop()
    if a.typeId == tyInt and b.typeId == tyFloat:
      stack.push(initValue(`op`(toFloat(a.intVal), b.floatVal)))
    elif a.typeId == tyFloat and b.typeId == tyInt:
      stack.push(initValue(`op`(a.floatVal, toFloat(b.intVal))))
    else:
      stack.push(initValue(`op`(a.someVal, b.someVal)))
    
    # additional debug output for stack operations
    when defined(hayaVmWriteStackOps):
      echo "binary in-place op: ", op, " a=", a, " b=", b

  template storeFrame() =
    # additional debug output for stack operations
    when defined(hayaVmWriteStackOps):
      display(span("store_frame:", fgYellow),
          span("pcIdx=" & $pcIdx & " stackBottom=" & $stackBottom &
               " currentChunk=" & $currentChunk))
    callStack.add(
      (
        currentChunk: currentChunk,
        cachedOps: co,
        pcIdx: pcIdx,
        stackBottom: stackBottom,
        script: script
      )
    )
  
  template restoreFrame() =
    stack.setLen(stackBottom)
    let frame = callStack.pop()
    currentChunk = frame.currentChunk
    script = frame.script
    co = frame.cachedOps
    cached = co
    pcIdx = frame.pcIdx
    stackBottom = frame.stackBottom

    # Defensive: ensure pcIdx is valid
    if pcIdx < 0 or pcIdx >= co.opcodes.len:
      pcIdx = co.opcodes.len - 1

    when defined(hayaVmWriteStackOps):
      display(span("restore_frame:", fgYellow),
              span("pcIdx=" & $pcIdx & " stackBottom=" & $stackBottom & " currentChunk=" & $currentChunk))

  template reloadChunk(newChunk: Chunk, newScript: Script) =
    # switch to a new chunk and script
    currentChunk = newChunk
    script = newScript
    cached = vm.getCachedOps(currentChunk)
    co = cached
    pcIdx = 0
    frameChanged = true
    
    # additional debug output for stack operations
    when defined(hayaVmWriteStackOps):
      echo "Reloaded currentChunk: ", currentChunk, " script=", script, " pcIdx=", pcIdx

  proc ensureLocal(idx: int) =
    let needed = stackBottom + idx
    while stack.len <= needed:
      stack.push(initValue(999)) # placeholder
    
    # additional debug output for stack operations
    when defined(hayaVmWriteStackOps):
      display(span("Ensure local:", fgCyan),
        span("idx=" & $idx & " stackLen=" & $stack.len))

  # Voodoo placeholder for injecting custom code at the start of the main loop
  conditionalPlaceholder"VanCodeVMBeforeMainLoop"

  # Main execution loop
  while true:
    # {.computedGoto.}
    frameChanged = false
    if pcIdx < 0 or pcIdx >= co.opcodes.len: break
    let oc = co.opcodes[pcIdx]
    
    # single debug output for opcode/stack at top of loop
    when defined(hayaVmWriteStackOps):
      display(span("OPCODE:", fgMagenta),
              span($oc), span("chunk=" & $currentChunk & " pcIdx=" & $pcIdx & " stack=" & $stack))
    
    # Main opcode dispatch
    extendableCase "vmInterpretCase":
      case oc
      #
      # Constants / simple pushes
      #
      of opcPushNil:
        stack.push(initObject(co.getArg1Int(pcIdx).uint16, nilObject))
      of opcPushI, opcPushF, opcPushS:
        co.pushConst(pcIdx, currentChunk, stack)
      of opcPushTrue:
        stack.push(initValue(true))
      of opcPushFalse:
        stack.push(initValue(false))
      of opcPushProc:
        let procScript = co.getArg1Str(pcIdx, currentChunk)
        let pid = co.arg2[pcIdx].int
        stack.push(initValue(pid, procScript))
      #
      # Variables
      #
      of opcPushG:
        # The `opcPushG` pushes a global variable onto the stack.
        stack.push(globals[co.getArg1Str(pcIdx, currentChunk)])
      of opcPopG:
        # The `opcPopG` pops the top of the stack and stores it in a global variable.
        let val = stack.pop()
        globals[co.getArg1Str(pcIdx, currentChunk)] = val
      of opcPushL:
        let idx = co.getArg1Int(pcIdx)
        ensureLocal(idx)
        stack.push(stack[stackBottom + idx])
      of opcPopL:
        let idx = co.getArg1Int(pcIdx)
        let val = stack.pop()
        ensureLocal(idx)
        stack[stackBottom + idx] = val
      of opcIncL:
        let idx = co.getArg1Int(pcIdx)
        ensureLocal(idx)
        stack[stackBottom + idx].intVal.inc
      of opcDecL:
        let idx = co.getArg1Int(pcIdx)
        ensureLocal(idx)
        stack[stackBottom + idx].intVal.dec
      #
      # Arrays / Objects
      #
      of opcConstrArray:
        let count = co.getArg1Int(pcIdx)
        var arr = initArray(count)
        if count > 0:
          let vals = stack{^count}
          for i in 0..<count:
            arr.objectVal.fields[i] = vals[i].toStorage
          stack.setLen(stack.len - count)
        stack.push(arr)
      of opcGetI:
        let idxVal = stack.pop()
        let arr = stack.pop()
        stack.push(arr.objectVal.fields[idxVal.intVal].toValue)
      of opcSetI:
        let
          val = stack.pop()
          idxVal = stack.pop()
          arr = stack.pop()
        arr.objectVal.fields[idxVal.intVal] = val.toStorage
      of opcConstrObj:
        let count = co.getArg1Int(pcIdx)
        var obj = initObject(15, count)
        if count > 0:
          let needPairs = count * 2
          # dynamic object storage => stack has (key, value) pairs
          var canUsePairs = stack.len >= needPairs
          if canUsePairs:
            let vals = stack{^needPairs}
            for i in 0 ..< count:
              if vals[2 * i].typeId != tyString:
                canUsePairs = false
                break
            if canUsePairs:
              for i in 0 ..< count:
                let fieldKey = vals[2 * i]
                let fieldValue = vals[2 * i + 1]
                obj.objectVal.keys.add(fieldKey.stringVal[])
                obj.objectVal.fields[i] = fieldValue.toStorage
              stack.setLen(stack.len - needPairs)
          # typed object constructor => stack has values only
          if not canUsePairs:
            if stack.len < count:
              raise newException(IndexDefect,
                "opcConstrObj stack underflow: need " & $count &
                " values (or " & $needPairs & " key/value items), have " & $stack.len)
            let vals = stack{^count}
            for i in 0 ..< count:
              obj.objectVal.fields[i] = vals[i].toStorage
            stack.setLen(stack.len - count)
        stack.push(obj)
      
      of opcGetF:
        let fld = co.getArg1Int(pcIdx)
        let obj = stack.pop()
        stack.push(obj.objectVal.fields[fld].toValue)
      
      of opcSetF:
        let fld = co.getArg1Int(pcIdx)
        let val = stack.pop()
        let obj = stack.pop()
        obj.objectVal.fields[fld] = val.toStorage
      
      #
      # JSON (placeholders)
      #
      of opcGetJ:
        let key = stack.pop()
        let obj = stack.pop()
        var jsonValue: JsonNode # the value to be pushed onto the stack
        case key.typeId
        of tyInt:
          jsonValue = obj.jsonVal[key.intVal]
        of tyString:
          jsonValue = obj.jsonVal[key.stringVal[]]
        else: discard
        stack.push(initValue(jsonValue))
      of opcSetJ:
        discard # TODO
      #
      # Discard
      #
      of opcDiscard:
        let n = co.getArg1Int(pcIdx)
        if n > 0 and stack.len >= n:
          stack.setLen(stack.len - n)
      #
      # Arithmetic
      #
      of opcNegI:
        let a = stack.pop(); stack.push(initValue(-a.intVal))
      of opcAddI, opcSubI, opcMultI, opcDivI:
        let b = stack.pop() # rhs arg
        let a = stack.pop() # lhs arg
        case oc
          of opcAddI: stack.push(initValue(a.intVal + b.intVal))
          of opcSubI: stack.push(initValue(a.intVal - b.intVal))
          of opcMultI: stack.push(initValue(a.intVal * b.intVal))
          of opcDivI: stack.push(initValue(a.intVal div b.intVal))
          else: discard
      of opcNegF:
        let a = stack.pop()
        stack.push(initValue(-a.floatVal))
      of opcAddF, opcSubF, opcMultF, opcDivF:
        let b = stack.pop()
        let a = stack.pop()
        let av = if a.typeId == tyInt: a.intVal.toFloat else: a.floatVal
        let bv = if b.typeId == tyInt: b.intVal.toFloat else: b.floatVal
        case oc
          of opcAddF: stack.push(initValue(av + bv))
          of opcSubF: stack.push(initValue(av - bv))
          of opcMultF: stack.push(initValue(av * bv))
          of opcDivF: stack.push(initValue(av / bv))
          else: discard
      #
      # String operations
      #
      of opcConcatStr:
        let b = stack.pop()
        let a = stack.pop()
        var result = Value(typeId: tyString)
        new(result.stringVal)
        result.stringVal[] = a.stringVal[] & b.stringVal[]
        stack.push(result)
      #
      # Logic
      #
      of opcInvB:
        let a = stack.pop()
        stack.push(initValue(not a.boolVal))
      of opcEqB:
        let b = stack.pop()
        let a = stack.pop()
        stack.push(initValue(a.boolVal == b.boolVal))
      of opcEqI:
        let b = stack.pop()
        let a = stack.pop()
        stack.push(initValue(a.intVal == b.intVal))
      of opcLessI:
        let b = stack.pop()
        let a = stack.pop()
        stack.push(initValue(a.intVal < b.intVal))
      of opcGreaterI:
        let b = stack.pop()
        let a = stack.pop()
        stack.push(initValue(a.intVal > b.intVal))
      of opcEqF, opcLessF, opcGreaterF:
        let b = stack.pop()
        let a = stack.pop()
        let 
          av = if a.typeId == tyInt: a.intVal.toFloat else: a.floatVal
          bv = if b.typeId == tyInt: b.intVal.toFloat else: b.floatVal
        case oc
          of opcEqF:
            stack.push(initValue(av == bv))
          of opcLessF:
            stack.push(initValue(av < bv))
          of opcGreaterF:
            stack.push(initValue(av > bv))
          else: discard
      #
      # Modules
      #
      of opcImportModule:
        let chunkPath = co.getArg1Str(pcIdx, currentChunk)
        let other = script.scripts[chunkPath]
        storeFrame()
        
        stackBottom = stack.len
        inc(vm.lvl) # increase module import level
        
        # switch to the imported module's main chunk
        reloadChunk(other.mainChunk, other)

        when defined(hayaVmWriteStackOps):
          display(span("import:", fgGreen), span(chunkPath), span($currentChunk))
        
        continue # jump to new chunk
      of opcImportModuleAlias, opcImportFromModule: discard # todo
      #
      # Control Flow
      #
      of opcJumpFwd:
        let tgt = co.jumpTargets[pcIdx]
        # Hot loop detection for backward jumps using opcJumpFwd
        if vm.preferences.enableHotCodeDetection and tgt >= 0 and tgt < pcIdx:
          let cnt = currentChunk.hotLoopCount
          if cnt < vm.preferences.hotLoopThreshold:
            currentChunk.hotLoopCount = cnt + 1
          elif not currentChunk.hotLoopCompiled:
            currentChunk.hotLoopCompiled = true
            when defined(vancodeJitLog):
              stderr.writeLine "[jit] hotLoop threshold reached"
            when defined(vancodeJit) or defined(vancodeJitLlvm) or defined(vancodeJitGcc):
              if vm.jit.getForeign != nil and currentChunk != script.mainChunk:
                var owningProc: Proc = nil
                for i in 0..<script.procs.len:
                  let p = script.procs[i]
                  if p.kind == pkNative and p.chunk == currentChunk:
                    owningProc = p
                    break
                when defined(vancodeJitLog):
                  if owningProc != nil: stderr.writeLine "[jit] found proc: " & owningProc.name
                  else: stderr.writeLine "[jit] owningProc NOT FOUND"
                if owningProc != nil:
                  currentChunk.hotLoopOwner = owningProc
                  let jitFn = vm.jit.getForeign(cast[pointer](owningProc))
                  if jitFn != nil:
                    when defined(vancodeJitLog): stderr.writeLine "[jit] sync compile OK, executing"
                    owningProc.jitForeign = jitFn
                    var savedArgs: seq[Value]
                    if owningProc.paramCount > 0:
                      savedArgs = newSeq[Value](owningProc.paramCount)
                      for i in 0..<owningProc.paramCount:
                        savedArgs[i] = stack[stackBottom + i]
                    restoreFrame()
                    inc(pcIdx)
                    let callResult =
                      if owningProc.paramCount > 0:
                        jitFn(cast[StackView](addr savedArgs[0]), owningProc.paramCount)
                      else:
                        jitFn(nil, 0)
                    if owningProc.hasResult:
                      stack.push(callResult)
                    continue
                  else:
                    when defined(vancodeJitLog): stderr.writeLine "[jit] queue async compile"
                    currentChunk.hotLoopQueued = true
                    if vm.jit.queueCompile != nil:
                      vm.jit.queueCompile(cast[pointer](owningProc))
          elif currentChunk.hotLoopQueued and currentChunk.hotLoopOwner != nil:
            let owningProc = currentChunk.hotLoopOwner
            if owningProc.jitForeign != nil:
              when defined(vancodeJitLog): stderr.writeLine "[jit] async compile done, executing"
              currentChunk.hotLoopQueued = false
              let jitFn = owningProc.jitForeign
              var savedArgs: seq[Value]
              if owningProc.paramCount > 0:
                savedArgs = newSeq[Value](owningProc.paramCount)
                for i in 0..<owningProc.paramCount:
                  savedArgs[i] = stack[stackBottom + i]
              restoreFrame()
              inc(pcIdx)
              let callResult =
                if owningProc.paramCount > 0:
                  jitFn(cast[StackView](addr savedArgs[0]), owningProc.paramCount)
                else:
                  jitFn(nil, 0)
              if owningProc.hasResult:
                stack.push(callResult)
              continue
        if tgt >= 0: pcIdx = tgt - 1
      of opcJumpFwdT:
        # jump if true
        let val = stack.peek()
        let cond = 
          case val.typeId
          of tyBool: val.boolVal
          of tyJsonStorage:
            val.jsonVal != nil and val.jsonVal.kind == JBool and val.jsonVal.bVal
          else: false
        if cond:
          let tgt = co.jumpTargets[pcIdx]
          if tgt >= 0: pcIdx = tgt - 1
          when defined(hayaVmWriteStackOps):
            echo "JumpFwdT: tgt=", tgt, " cond=", cond
      of opcJumpFwdF:
        # jump if false
        let val = stack.peek()
        let cond = 
          case val.typeId
          of tyBool: val.boolVal
          of tyJsonStorage:
            val.jsonVal != nil and val.jsonVal.kind == JBool and val.jsonVal.bVal
          else: false
        if not cond:
          let tgt = co.jumpTargets[pcIdx]
          if tgt >= 0: pcIdx = tgt - 1
          when defined(hayaVmWriteStackOps):
            echo "JumpFwdF: tgt=", tgt, " cond=", cond
      of opcJumpBack:
        let tgt = co.jumpTargets[pcIdx]
        # Hot loop detection for backward jumps using opcJumpBack
        if vm.preferences.enableHotCodeDetection and tgt >= 0 and tgt < pcIdx:
          let cnt = currentChunk.hotLoopCount
          if cnt < vm.preferences.hotLoopThreshold:
            currentChunk.hotLoopCount = cnt + 1
          elif not currentChunk.hotLoopCompiled:
            currentChunk.hotLoopCompiled = true
            when defined(vancodeJitLog):
              stderr.writeLine "[jit] hotLoop threshold reached"
            when defined(vancodeJit) or defined(vancodeJitLlvm) or defined(vancodeJitGcc):
              if vm.jit.getForeign != nil and currentChunk != script.mainChunk:
                var owningProc: Proc = nil
                for i in 0..<script.procs.len:
                  let p = script.procs[i]
                  if p.kind == pkNative and p.chunk == currentChunk:
                    owningProc = p
                    break
                when defined(vancodeJitLog):
                  if owningProc != nil: stderr.writeLine "[jit] found proc: " & owningProc.name
                  else: stderr.writeLine "[jit] owningProc NOT FOUND"
                if owningProc != nil:
                  currentChunk.hotLoopOwner = owningProc
                  let jitFn = vm.jit.getForeign(cast[pointer](owningProc))
                  if jitFn != nil:
                    when defined(vancodeJitLog): stderr.writeLine "[jit] sync compile OK, executing"
                    owningProc.jitForeign = jitFn
                    var savedArgs: seq[Value]
                    if owningProc.paramCount > 0:
                      savedArgs = newSeq[Value](owningProc.paramCount)
                      for i in 0..<owningProc.paramCount:
                        savedArgs[i] = stack[stackBottom + i]
                    restoreFrame()
                    inc(pcIdx)
                    let callResult =
                      if owningProc.paramCount > 0:
                        jitFn(cast[StackView](addr savedArgs[0]), owningProc.paramCount)
                      else:
                        jitFn(nil, 0)
                    if owningProc.hasResult:
                      stack.push(callResult)
                    continue
                  else:
                    when defined(vancodeJitLog): stderr.writeLine "[jit] queue async compile"
                    currentChunk.hotLoopQueued = true
                    if vm.jit.queueCompile != nil:
                      vm.jit.queueCompile(cast[pointer](owningProc))
          elif currentChunk.hotLoopQueued and currentChunk.hotLoopOwner != nil:
            let owningProc = currentChunk.hotLoopOwner
            if owningProc.jitForeign != nil:
              when defined(vancodeJitLog): stderr.writeLine "[jit] async compile done, executing"
              currentChunk.hotLoopQueued = false
              let jitFn = owningProc.jitForeign
              var savedArgs: seq[Value]
              if owningProc.paramCount > 0:
                savedArgs = newSeq[Value](owningProc.paramCount)
                for i in 0..<owningProc.paramCount:
                  savedArgs[i] = stack[stackBottom + i]
              restoreFrame()
              inc(pcIdx)
              let callResult =
                if owningProc.paramCount > 0:
                  jitFn(cast[StackView](addr savedArgs[0]), owningProc.paramCount)
                else:
                  jitFn(nil, 0)
              if owningProc.hasResult:
                stack.push(callResult)
              continue
        if tgt >= 0: pcIdx = tgt - 1
        when defined(hayaVmWriteStackOps):
          stderr.writeLine "jumpBack: pc=", pcIdx, " stack.len=", stack.len
      of opcCallD:
        # The `opcCallD` calls a procedure defined
        # in the current or another chunk.
        let chunkPath = co.getArg1Str(pcIdx, currentChunk)
        let procId = co.arg2[pcIdx].int
        # Resolve initial target script by path or current
        var targetScript =
          if chunkPath == currentChunk.file: script
          else:
            if chunkPath in script.scripts:
              script.scripts[chunkPath]
            else:
              # fallback to vm.importedModules if present
              if chunkPath in vm.importedModules:
                vm.importedModules[chunkPath]
              else:
                raise newException(ValueError,
                  "opcCallD: target module not found: " & chunkPath)

        let p = targetScript.procs[procId]
        vm.markHotProc(p)
        # Tail-call optimization: reuse the current frame for self-recursive
        # calls in tail position (next opcode is opcReturnVal).
        if p.kind == pkNative and p.chunk == currentChunk and
           pcIdx + 1 < co.opcodes.len and co.opcodes[pcIdx + 1] == opcReturnVal:
          if stack.len < p.paramCount:
            raise newException(ValueError,
              "Not enough arguments on stack for call to " & p.name & ": need " & $p.paramCount & ", have " & $stack.len)
          stackBottom = stack.len - p.paramCount
          currentChunk = p.chunk
          cached = vm.getCachedOps(currentChunk)
          co = cached
          pcIdx = 0
          continue
        storeFrame()
        if stack.len < p.paramCount:
          raise newException(ValueError,
            "Not enough arguments on stack for call to " & p.name & ": need " & $p.paramCount & ", have " & $stack.len)
        stackBottom = stack.len - p.paramCount

        # JIT fast path — use pre-compiled version if available
        if p.jitForeign != nil:
          let callResult =
            if p.paramCount > 0:
              p.jitForeign(stack{^p.paramCount}, p.paramCount)
            else:
              p.jitForeign(nil, 0)
          restoreFrame()
          if p.hasResult:
            stack.push(callResult)
          inc(pcIdx)
          continue
        # Async JIT fast path — check atomically-set code pointer
        let jitFnPtr = atomicLoadN(addr p.jitCodePtr, AtomicAcquire)
        if jitFnPtr != nil:
          type AsyncJitFn = proc (flatArgs: ptr int64, argc: int): int64 {.cdecl.}
          let fn = cast[AsyncJitFn](jitFnPtr)
          var flatArgs = newSeq[int64](max(max(p.jitMaxLocal, p.paramCount), 1))
          for i in 0..<p.paramCount:
            flatArgs[i] = stack[stack.len - p.paramCount + i].intVal
          let resultI = fn(addr flatArgs[0], p.paramCount)
          restoreFrame()
          if p.hasResult:
            if p.jitReturnBool:
              stack.push(Value(typeId: tyBool, boolVal: resultI != 0))
            else:
              stack.push(initValue(resultI))
          inc(pcIdx)
          continue

        when defined(hayaVmWriteStackOps):
          display(span("opc:", fgGreen), span("<" & $opcCallD & ">"),
            span("filePath=" & chunkPath & " procId=" & $procId & " name=" & p.name & " paramCount=" & $p.paramCount)) 
        case p.kind
        of pkNative:
          currentChunk = p.chunk
          cached = vm.getCachedOps(currentChunk)
          co = cached
          pcIdx = 0
          continue
        of pkForeign:
          let callResult =
            if p.paramCount > 0:
              p.foreign(stack{^p.paramCount}, p.paramCount)
            else:
              p.foreign(nil, 0)
          restoreFrame() # after foreign call
          if p.hasResult:
            stack.push(callResult)
          when defined(hayaVmWriteStackOps):
            if callResult != nil:
              echo "Foreign call result: ", callResult
            else:
              echo "Foreign call result: nil"
      of opcCallI:
        let argc = co.getArg1Int(pcIdx)
        let procBase = stack.len - argc - 1
        let procVal = stack[procBase]
        if procVal.typeId != tyProc:
          raise newException(ValueError, "opcCallI: expected a proc value")
        let pId = procVal.procVal.procId
        let pScript = procVal.procVal.procScript
        stack.delete(procBase)
        var targetScript: Script = nil
        if pScript == currentChunk.file: targetScript = script
        elif pScript in script.scripts: targetScript = script.scripts[pScript]
        elif pScript in vm.importedModules: targetScript = vm.importedModules[pScript]
        if targetScript == nil or pId < 0 or pId >= targetScript.procs.len:
          raise newException(ValueError, "opcCallI: target proc not found")
        let p = targetScript.procs[pId]
        vm.markHotProc(p)
        storeFrame()
        if stack.len < p.paramCount:
          raise newException(ValueError,
            "Not enough arguments on stack for call to " & p.name)
        stackBottom = stack.len - p.paramCount
        case p.kind
        of pkNative:
          currentChunk = p.chunk
          cached = vm.getCachedOps(currentChunk)
          co = cached
          pcIdx = 0
          continue
        of pkForeign:
          let callResult =
            if p.paramCount > 0:
              p.foreign(stack{^p.paramCount}, p.paramCount)
            else:
              p.foreign(nil, 0)
          restoreFrame()
          if vm.pendingCallback != nil:
            let cb = vm.pendingCallback
            vm.pendingCallback = nil
            if p.hasResult:
              stack.push(callResult)
            let cbId = cb.procVal.procId
            let cbScriptStr = cb.procVal.procScript
            var cbScript: Script = nil
            if cbScriptStr == currentChunk.file: cbScript = script
            elif cbScriptStr in script.scripts: cbScript = script.scripts[cbScriptStr]
            elif cbScriptStr in vm.importedModules: cbScript = vm.importedModules[cbScriptStr]
            if cbScript != nil and cbId >= 0 and cbId < cbScript.procs.len:
              let cbProc = cbScript.procs[cbId]
              if cbProc.kind == pkNative:
                storeFrame()
                stackBottom = stack.len - cbProc.paramCount
                currentChunk = cbProc.chunk
                cached = vm.getCachedOps(currentChunk)
                co = cached
                pcIdx = 0
                continue
          if p.hasResult:
            stack.push(callResult)
      of opcReturnVal:
        let rv = stack.pop()
        if stepping != nil:
          stepping.state = csCompleted
          stepping.result = rv
          return rv
        if callStack.len == 0:
          if vm.activeCoroutine != nil:
            let coro = vm.activeCoroutine
            coro.state = csCompleted
            coro.result = rv
            stack = vm.savedStack
            callStack = vm.savedCallStack
            pcIdx = vm.savedPcIdx
            currentChunk = vm.savedChunk
            co = vm.savedCo
            cached = co
            opcodes = co.opcodes
            stackBottom = vm.savedStackBottom
            script = vm.savedScript
            vm.activeCoroutine = nil
            stack.push(rv)
          else:
            return rv
        else:
          restoreFrame()
          stack.push(rv)
      of opcReturnVoid:
        if stepping != nil:
          stepping.state = csCompleted
          stepping.result = Value(typeId: tyNil)
          return Value(typeId: tyNil)
        if callStack.len == 0 and vm.activeCoroutine != nil:
          let coro = vm.activeCoroutine
          coro.state = csCompleted
          stack = vm.savedStack
          callStack = vm.savedCallStack
          pcIdx = vm.savedPcIdx
          currentChunk = vm.savedChunk
          co = vm.savedCo
          cached = co
          opcodes = co.opcodes
          stackBottom = vm.savedStackBottom
          script = vm.savedScript
          vm.activeCoroutine = nil
        else:
          restoreFrame()
        when defined(hayaVmWriteStackOps):
          display(span("return:", fgGreen), span("void", fgCyan))
      #
      # Coroutines
      #
      of opcCreateCoro:
        let pid = co.getArg1Int(pcIdx)
        if pid < 0 or pid >= script.procs.len:
          raise newException(ValueError,
            "opcCreateCoro: invalid proc id " & $pid)
        let p = script.procs[pid]
        if p.kind != pkNative:
          raise newException(ValueError,
            "opcCreateCoro: only native procs can be used as coroutines")
        let coro = Coroutine(state: csCreated, callee: p, script: script)
        stack.push(initValue[Coroutine](tyCoroutine, coro))
      of opcCoroResume:
        if stack.len == 0:
          raise newException(ValueError,
            "opcCoroResume: stack is empty")
        let coroVal = stack.pop()
        if coroVal.typeId != tyCoroutine:
          raise newException(ValueError,
            "opcCoroResume: expected a coroutine value, got typeId " & $coroVal.typeId)
        if coroVal.objectVal == nil or coroVal.objectVal.foreign.data == nil:
          raise newException(ValueError,
            "opcCoroResume: invalid coroutine value")
        let coro = cast[Coroutine](coroVal.objectVal.foreign.data)
        case coro.state
        of csCreated:
          let paramCount = coro.callee.paramCount
          if stack.len < paramCount:
            raise newException(ValueError,
              "opcCoroResume: not enough arguments on stack for coroutine" &
              " (need " & $paramCount & ", have " & $stack.len & ")")
          let argsStart = stack.len - paramCount
          vm.savedStack = stack[0..<argsStart]
          vm.savedCallStack = callStack
          vm.savedPcIdx = pcIdx
          vm.savedChunk = currentChunk
          vm.savedCo = co
          vm.savedStackBottom = stackBottom
          vm.savedScript = script
          vm.activeCoroutine = coro
          var coroStack = newSeqOfCap[Value](VMInitialPreallocatedStackSize)
          for i in 0..<paramCount:
            coroStack.add(stack[argsStart + i])
          stack = coroStack
          stackBottom = 0
          callStack = newSeqOfCap[CallFrame](256)
          let p = coro.callee
          script = coro.script
          currentChunk = p.chunk
          cached = vm.getCachedOps(currentChunk)
          co = cached
          opcodes = co.opcodes
          pcIdx = 0
          coro.state = csRunning
          continue
        of csSuspended:
          vm.savedStack = stack
          vm.savedCallStack = callStack
          vm.savedPcIdx = pcIdx
          vm.savedChunk = currentChunk
          vm.savedCo = co
          vm.savedStackBottom = stackBottom
          vm.savedScript = script
          stack = coro.savedStack
          callStack = coro.savedCallStack
          pcIdx = coro.savedPcIdx
          currentChunk = coro.savedChunk
          co = coro.savedCachedOps
          cached = co
          opcodes = co.opcodes
          stackBottom = coro.savedStackBottom
          script = coro.script
          vm.activeCoroutine = coro
          coro.state = csRunning
          continue
        of csRunning:
          raise newException(ValueError,
            "opcCoroResume: coroutine is already running")
        of csCompleted, csErrored:
          raise newException(ValueError,
            "opcCoroResume: coroutine is already completed")
      of opcCoroYield:
        if stepping != nil:
          let val = stack.pop()
          stepping.savedStack = stack
          stepping.savedCallStack = callStack
          stepping.savedPcIdx = pcIdx + 1
          stepping.savedChunk = currentChunk
          stepping.savedCachedOps = co
          stepping.savedStackBottom = stackBottom
          stepping.state = csSuspended
          stepping.result = val
          return val
        if vm.activeCoroutine == nil:
          raise newException(ValueError,
            "opcCoroYield: yield outside of a coroutine")
        if stack.len == 0:
          raise newException(ValueError,
            "opcCoroYield: stack is empty")
        let val = stack.pop()
        let coro = vm.activeCoroutine
        coro.savedStack = stack
        coro.savedCallStack = callStack
        coro.savedPcIdx = pcIdx + 1
        coro.savedChunk = currentChunk
        coro.savedCachedOps = co
        coro.savedStackBottom = stackBottom
        coro.state = csSuspended
        stack = vm.savedStack
        callStack = vm.savedCallStack
        pcIdx = vm.savedPcIdx
        currentChunk = vm.savedChunk
        co = vm.savedCo
        cached = co
        opcodes = co.opcodes
        stackBottom = vm.savedStackBottom
        script = vm.savedScript
        vm.activeCoroutine = nil
        stack.push(val)
      of opcHalt:
        if stepping != nil:
          stepping.state = csCompleted
          if stack.len > 0:
            stepping.result = stack[^1]
            return stepping.result
          else:
            stepping.result = Value(typeId: tyNil)
            return stepping.result
        when defined(hayaVmWriteStackOps):
          if stack.len > 0:
            echo "Warning: stack not empty at halt, contains ", stack.len, " items."
          display(span("*** halt", fgRed), span("lvl=" & $vm.lvl))
        if vm.lvl == 0:
          break # top-level halt
        else:
          restoreFrame()
          dec(vm.lvl)
      of opcNoop: discard
      else: discard # unhandled opcode (should not happen if parser is correct)
    inc(pcIdx)
  
  if stepping != nil and stepping.state == csRunning:
    stepping.state = csCompleted
    stepping.result = if stack.len > 0: stack[^1] else: Value(typeId: tyNil)
    return stepping.result

  if result == nil or result.typeId == tyNil:
    if stack.len > 0:
      # when defined(vancodeJit) or defined(vancodeJitLlvm) or defined(vancodeJitGcc):
      #   stderr.writeLine "DEBUG: stack.len at end = " & $stack.len & " last.typeId = " & $stack[^1].typeId
      return stack[^1]
    else:
      return Value(typeId: tyNil)

proc stepCoroutine*(vm: Vm, coro: Coroutine): CoroutineResult =
  if coro.state notin {csCreated, csSuspended}:
    return CoroutineResult(kind: crErrored,
      errorMsg: "stepCoroutine: coroutine is in invalid state " & $coro.state)
  let startChunk =
    if coro.state == csSuspended: coro.savedChunk
    else: coro.callee.chunk
  var r: Value
  {.cast(gcsafe).}:
    r = vm.interpret(coro.script, startChunk, stepping = coro)
  case coro.state
  of csSuspended:
    CoroutineResult(kind: crYielded, yieldedValue: r)
  of csCompleted:
    CoroutineResult(kind: crCompleted, resultValue: r)
  of csErrored:
    CoroutineResult(kind: crErrored)
  else:
    CoroutineResult(kind: crErrored,
      errorMsg: "stepCoroutine: unexpected final state " & $coro.state)