name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
jobs:
  test:
    uses: nimbase/setup-nim-action/.github/workflows/test_clue.yml@main
    with:
      nim-version: stable
      os: '[{"os":"ubuntu-latest"},{"os":"macos-15"},{"os":"macos-15-intel"}]'
